"""
Performance utilities: caching headers, critical CSS extraction,
responsive image helpers, and compression hints.
"""
from functools import lru_cache
from pathlib import Path

from flask import Flask, Response, request


# === Cache control middleware ===

def add_cache_headers(app: Flask) -> None:
    """
    Add sensible cache headers to all responses.
    Static assets: long cache (fingerprinted by Flask).
    HTML pages: short cache with revalidation.
    API responses: no cache.
    """
    @app.after_request
    def set_cache(response: Response) -> Response:
        if request.endpoint and request.endpoint.startswith("static"):
            # Static files are fingerprinted — cache aggressively
            response.cache_control.public = True
            response.cache_control.max_age = 60 * 60 * 24 * 365  # 1 year
            response.cache_control.immutable = True
        elif request.path.startswith("/api/"):
            # API responses — no cache
            response.cache_control.no_store = True
            response.cache_control.no_cache = True
        elif response.content_type and "text/html" in response.content_type:
            # HTML pages — short cache with revalidation
            response.cache_control.public = True
            response.cache_control.max_age = 60  # 1 minute
            response.vary.add("Cookie")
        return response


# === Security headers ===

def add_security_headers(app: Flask) -> None:
    """Add baseline security headers to all responses."""
    @app.after_request
    def set_security(response: Response) -> Response:
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "SAMEORIGIN"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
        response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
        # CSP: allow self, inline styles (needed for theme engine), fonts, images
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            "script-src 'self' 'unsafe-inline' https://esm.sh; "
            "connect-src 'self' https://esm.sh; "
            "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
            "img-src 'self' data: blob: https://i.ytimg.com https://yt3.ggpht.com https://*.supabase.co; "
            "font-src 'self' https://fonts.gstatic.com; "
            "media-src 'self' blob: https://*.supabase.co; "
            "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com; "
            "frame-ancestors 'self'"
        )
        return response


# === Responsive image helpers ===

def responsive_srcset(image_path: str, sizes: tuple = ("small", "medium", "large")) -> str:
    """
    Build a srcset attribute for responsive images stored in Supabase Storage.
    Expects thumbnails generated by media_service.save_upload() (which always
    generates all three sizes for image uploads, so no existence check is
    needed here -- this just resolves each thumbnail's public URL).
    Example output: "https://.../small.webp 400w, https://.../medium.webp 800w, ..."
    """
    if not image_path:
        return ""

    from app.services.media_service import get_thumbnail_url

    widths = {"small": 400, "medium": 800, "large": 1600}

    parts = []
    for size in sizes:
        url = get_thumbnail_url(image_path, size)
        if url:
            parts.append(f"{url} {widths[size]}w")

    return ", ".join(parts)


def responsive_sizes(hint: str = "default") -> str:
    """Return a sizes attribute based on layout context."""
    hints = {
        "default": "(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw",
        "hero": "100vw",
        "article": "(max-width: 768px) 100vw, 760px",
        "thumbnail": "(max-width: 768px) 50vw, 200px",
        "gallery": "(max-width: 600px) 100vw, (max-width: 900px) 50vw, 33vw",
    }
    return hints.get(hint, hints["default"])


# === Critical CSS ===

@lru_cache(maxsize=1)
def get_critical_css() -> str:
    """
    Return the critical above-the-fold CSS inlined in <head>.
    Kept small (< 14KB) to avoid render-blocking.
    Includes: reset, typography, header, hero, first story card.
    """
    return """
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    html{scroll-behavior:smooth}
    body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
         background:var(--background,#fff);color:var(--text,#111418);line-height:1.6;
         -webkit-font-smoothing:antialiased}
    h1,h2,h3,h4{font-family:'Merriweather',Georgia,serif;line-height:1.25;letter-spacing:-0.01em}
    a{color:var(--brand-primary,#0B3C8C);text-decoration:none}
    img{max-width:100%;height:auto;display:block}
    .container{max-width:1280px;margin:0 auto;padding:0 16px}
    @media(min-width:768px){.container{padding:0 24px}}
    @media(min-width:1024px){.container{padding:0 32px}}
    .site-header{background:var(--brand-secondary,#0A1F44);color:#fff;
                 border-bottom:3px solid var(--accent,#D4A537);
                 position:sticky;top:0;z-index:100}
    .header-inner{display:flex;align-items:center;justify-content:space-between;padding:14px 0}
    .logo{font-family:'Merriweather',serif;font-size:22px;font-weight:900;color:#fff}
    .logo span{color:var(--accent,#D4A537)}
    .skip-link{position:absolute;left:-9999px;top:0;background:var(--brand-primary);
               color:#fff;padding:8px 16px;z-index:1000}
    .skip-link:focus{left:0}
    """